- hosts: localhost
  become: true
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - virtualenv
          - python3-setuptools
          - gnupg
        state: latest
        update_cache: true

    - name: install python3
      ansible.builtin.apt:
        name: python3
        state: present

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        allow_downgrade: yes
        clean: true

    - name: Install LetEncrypts and certbots utils
      ansible.builtin.apt:
        pkg:
          - certbot
          - python3-certbot-nginx
        state: present

    - name: install pip3 package manager
      ansible.builtin.apt:
        name: python3-pip
        state: present
        allow_downgrade: yes

    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: yes

    - name: Add docker gpg
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: ensure docker installation
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        allow_downgrade: yes
        update_cache: yes

    - name: Check If Docker Is Installed
      command: docker --version
      register: docker_valid
      ignore_errors: yes

    - name: Retrieve lazy-docker installation binary
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh
        dest: /tmp/install-lazydocker.sh

    - name: Execute lazy-docker installation script
      shell: /tmp/install-lazydocker.sh
      when: download.changed

    - name: Remove lazy-docker script
      file:
        path: /tmp/install-lazydocker.sh
        present: absent
