# docker-compose.yaml
version: "3.8"
services:
  jenkins:
    image: ${JENKIN_IMAGE}:latest
    build:
      dockerfile: Dockerfile
      context: ./
    privileged: true
    user: root
    restart: always
    ports:
      - ${PRIMARY_PORT}:8080
      - ${SECONDARY_PORT}:50000
    container_name: jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins:
    name: jenkins-network
    driver: bridge
