- name: Check if lazy-docker install
  command: lazydocker --version
  ignore_errors: true
  register: installed

- name: Retrieve lazy-docker installation binary
  ansible.builtin.get_url:
    url: "{{ lazy_docker_url }}"
    dest: /tmp/install-lazydocker.sh
    mode: 0755
  when: installed.rc != 0
  register: download

- name: Run lazy-docker installation script
  shell: echo "installation began"
  when: installed.rc != 0
  notify:
    - pull lazydocker-script
    - clean lazydocker-script
    - link global-lazydocker
