---
- name: Check If Docker Is Installed
  command: docker --version
  register: docker_valid
  ignore_errors: true

- name: Ensure Docker is Installed
  apt:
    name: docker.io
    state: present
    update_cache: true
  when: docker_valid.rc != 0

- name: Add docker gpg
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Check If Docker Is Installed
  command: docker --version
  register: docker_valid
  ignore_errors: true

- name: Enable and start Docker service
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true
  when: docker_valid.rc== 0

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user jenkins to Docker group
  user:
    name: "{{ primary_user }}"
    groups: docker
    append: yes

- name: Check if lazy-docker install
  command: lazydocker --version
  ignore_errors: true
  register: installed

- name: Retrieve lazy-docker installation binary
  ansible.builtin.get_url:
    url: "{{ lazy_docker_url }}"
    dest: /tmp/install-lazydocker.sh
    mode: "u+rw"
  when: installed.rc != 0
  register: download

- name: Execute lazy-docker installation script
  shell: bash /tmp/install-lazydocker.sh

- name: Remove lazy-docker script
  file:
    path: /tmp/install-lazydocker.sh
    state: absent
