- hosts: localhost
  become: true
  tasks:
    - name: Ensure certbot service is enabled
      service:
        name: certbot.timer
        state: started
    - name: Ensure crontab is installed
      apt:
        name: cron
        state: present
        update_cache: yes
  vars:
    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_auto_renew_hour: "5"
    certbot_auto_renew_minute: "30"
    certbot_auto_renew_options: "--quiet"
    certbot_certs:
      - email: lusomreth@gmail.com
      # shell: certbot -d {{ https_domain_url }} --nginx

  handlers:
    - name: restart certbot
      service:
        name: certbot.timer
        state: restarted
  roles:
    - geerlingguy.certbot
