- hosts: "{{ target_server }}"
  gather_facts: false
  become: true
  tasks:
    - name: Ensure certbot service is enabled
      service:
        name: certbot.timer
        state: started

    - name: Ensure crontab is installed
      apt:
        name:
          - certbot
          - cron
        state: present
        update_cache: yes
    - name: issuing the certificate
      shell: |
        certbot -n register --agree-tos --email "{{ ssl_admin_email }}"
        touch /etc/letsencrypt/.registered
      args:
        creates: /etc/letsencrypt/.registered
      tags:
        - nginx
        - certbot

    - name: running certbot registration
      command: certbot --nginx -d "{{ https_domain_url }}" -d "www.{{ https_domain_url }}"
      args:
        creates: "/etc/letsencrypt/live/{{ https_domain_url }}"

    - name: Setup cronjob for renewal
      cron:
        name: certbot-renewal
        job: "/bin/bash -lc '/usr/local/bin/certbot -q renew'"
        minute: "0"
        hour: "14"
      tags:
        - nginx
        - certbot

  handlers:
    - name: restart certbot
      service:
        name: certbot.timer
        state: restarted
