- hosts: localhost
  become: true
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg-agent
          - virtualenv
          - python3-setuptools
          - gnupg
        state: latest
        update_cache: true

    - name: install python3
      ansible.builtin.apt:
        name: python3
        state: present

    - name: install pip3 package manager
      ansible.builtin.apt:
        name: python3-pip
        state: present
        allow_downgrade: yes

    - name: install fish shell
      ansible.builtin.apt:
        name: fish
        state: present

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        allow_downgrade: yes
        clean: true

    - name: Install LetEncrypts and certbots utils
      ansible.builtin.apt:
        pkg:
          - certbot
          - python3-certbot-nginx
        state: present

    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: yes

  roles:
    - docker
