---
- hosts: staging_server
  become_user: "{{ ansible_user }}"
  # become: true
  vars:
    JENKINS_HOME_PATH: "{{ ansible_env.HOME }}/{{ JENKINS_HOME }}"
  tasks:
    - name: Make jenkins home dir
      file:
        dest: "{{ JENKINS_HOME_PATH }}"
        state: directory

    - name: Inject jenkin dockerfile
      copy:
        content: |
          FROM jenkins/jenkins
          USER root

          RUN apt-get update
          RUN apt-get install -y ansible

          USER jenkins
        dest: "{{ JENKINS_HOME_PATH }}/Dockerfile"
        owner: "{{ ansible_user }}"

    - name: build jenkin image
      become_user: "{{ ansible_user }}"
      docker_image:
        build:
          path: "{{ JENKINS_HOME_PATH }}"
        source: build
        name: "jenkin-server"
        tag: latest

    - name: clean up
      docker_prune:
        builder_cache: true
        images: true
